import { GeistSans } from 'geist/font/sans';
import type { Metadata } from 'next';
import { ThemeProvider } from 'next-themes';
import { CosmosProvider, NillionProvider } from '~/providers';
import '~/styles/globals.css';

import { Toaster } from '~/components/ui/sonner';
import { Navbar } from '~/components';

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang='en'>
      <body className={`font-sans ${GeistSans.variable}`}>
        <ThemeProvider>
          <CosmosProvider>
            <NillionProvider>
              <Navbar />
              {children}
              <Toaster />
            </NillionProvider>
          </CosmosProvider>
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
